/**
 * Django ORM models.py generator with field definitions
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: DJANGO\n`;
};
