/**
 * Express.js CRUD REST API controller and router boilerplate generator
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: EXPRESSROUTER\n`;
};
