/**
 * Go Struct generator with JSON, BSON, and GORM struct tags
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: GOLANG\n`;
};
