/**
 * GraphQL SDL TypeDefs generator with query and mutation scaffolding
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: GRAPHQL\n`;
};
