/**
 * Mermaid.js erDiagram syntax generator for visual documentation
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: MERMAID\n`;
};
