/**
 * Faker-style realistic Mock Data JSON generator
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: MOCKJSON\n`;
};
