/**
 * Mongoose schema compiler with nested sub-documents and timestamps
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: MONGOOSE\n`;
};
