/**
 * MySQL DDL table generation supporting engine specs and AUTO_INCREMENT
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: MYSQL\n`;
};
