/**
 * OpenAPI 3.0 YAML specification generator from visual schema
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: OPENAPI\n`;
};
