/**
 * PlantUML Entity-Relationship diagram generator
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: PLANTUML\n`;
};
