/**
 * Prisma ORM schema generator supporting relational models and enums
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: PRISMA\n`;
};
