/**
 * Rust Struct generator with Serde serialize/deserialize derives
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: RUST\n`;
};
