/**
 * SQLite table DDL generator with strict typing clauses
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: SQLITE\n`;
};
