/**
 * TypeORM entity classes generator with TypeScript decorators
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: TYPEORM\n`;
};
