/**
 * TypeScript interface & DTO type definition exporter
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: TYPESCRIPT\n`;
};
