/**
 * Zod runtime validation schema synthesizer
 */
exports.generate = (schemaData) => {
  const { name, fields = [], timestamps = true } = schemaData;
  return `// Generated by SchemaForge for ${name}\n// Target: ZOD\n`;
};
